package dev.onyx.server.engine.net

enum class StatusResponse(val code: Int) : Message {
    SUCCESSFUL(0),
    DELAY(1),
    NORMAL(2),
    INVALID_CREDENTIALS(3),
    ACCOUNT_DISABLED(4),
    ACCOUNT_ONLINE(5),
    OUT_OF_DATE(6),
    WORLD_FULL(7),
    SERVER_OFFLINE(8),
    BAD_SESSION_ID(10),
    ACCOUNT_LOCKED(11),
    MEMBERS_WORLD(12),
    COULD_NOT_COMPLETE_LOGIN(13),
    SERVER_UPDATE(14),
    LOGIN_ATTEMPTS_EXCEEDED(16),
    MEMBERS_ONLY_AREA(17),
    BETA_WORLD(19),
    INVALID_LOGIN_SERVER(20),
    MALFORMED_PACKET(22),
    NO_LOGIN_SERVER_RESPONSE(23),
    NO_DISPLAY_NAME(31),
    VOTE_TO_PLAY(38),
    MULTI_FACTOR_AUTH(56),
    INCORRECT_AUTH(57);
}